version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.1.0
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Set up udagram required environment variable
          command: |
            echo 'export NODE_OPTIONS=--openssl-legacy-provider' >> $BASH_ENV
      # install dependencies in both apps
      - run:
          name: Install Front End Dependencies
          command: |
            npm run install_frontend
      - run:          
          name: Install API Dependencies
          command: |
            npm run install_api
      #Conduct Continuous Integration Build
      - run:          
          name: Build Front End
          command: |
            npm run build_frontend
      - run:          
          name: Build the API
          command: |
            npm run build_api
        
